using System;
using System.Collections.Generic;
using OpenSage.Data.Ini.Parser;

namespace OpenSage.Logic.Object
{
    public abstract class ObjectBehavior : ObjectModule
    {
        internal static ObjectBehavior ParseBehavior(IniParser parser) => ParseModule(parser, BehaviorParseTable);

        private static readonly Dictionary<string, Func<IniParser, ObjectBehavior>> BehaviorParseTable = new Dictionary<string, Func<IniParser, ObjectBehavior>>
        {
            { "AIUpdateInterface", AIUpdateInterface.Parse },
            { "AutoDepositUpdate", AutoDepositUpdate.Parse },
            { "AutoHealBehavior", AutoHealBehavior.Parse },
            { "BaikonurLaunchPower", BaikonurLaunchPower.Parse },
            { "BaseRegenerateUpdate", BaseRegenerateUpdate.Parse },
            { "BoneFXDamage", BoneFXDamage.Parse },
            { "BoneFXUpdate", BoneFXUpdate.Parse },
            { "BridgeBehavior", BridgeBehavior.Parse },
            { "BridgeTowerBehavior", BridgeTowerBehavior.Parse },
            { "CashBountyPower", CashBountyPower.Parse },
            { "CashHackSpecialPower", CashHackSpecialPower.Parse },
            { "CostModifierUpgrade", CostModifierUpgrade.Parse },
            { "CreateCrateDie", CreateCrateDie.Parse },
            { "CreateObjectDie", CreateObjectDie.Parse },
            { "CrushDie", CrushDie.Parse },
            { "DamDie", DamDie.Parse },
            { "DefaultProductionExitUpdate", DefaultProductionExitUpdate.Parse },
            { "DefectorSpecialPower", DefectorSpecialPower.Parse },
            { "DeletionUpdate", DeletionUpdate.Parse },
            { "DestroyDie", DestroyDie.Parse },
            { "FireWeaponWhenDeadBehavior", FireWeaponWhenDeadBehavior.Parse },
            { "FireWeaponWhenDamagedBehavior", FireWeaponWhenDamagedBehavior.Parse },
            { "FlammableUpdate", FlammableUpdate.Parse },
            { "FloatUpdate", FloatUpdate.Parse },
            { "FXListDie", FXListDie.Parse },
            { "GarrisonContain", GarrisonContain.Parse },
            { "GenerateMinefieldBehavior", GenerateMinefieldBehavior.Parse },
            { "GrantUpgradeCreate", GrantUpgradeCreate.Parse },
            { "InstantDeathBehavior", InstantDeathBehavior.Parse },
            { "KeepObjectDie", KeepObjectDie.Parse },
            { "LifetimeUpdate", LifetimeUpdate.Parse },
            { "MoneyCrateCollide", MoneyCrateCollide.Parse },
            { "OCLSpecialPower", OCLSpecialPower.Parse },
            { "ParticleUplinkCannonUpdate", ParticleUplinkCannonUpdate.Parse },
            { "PhysicsBehavior", PhysicsBehavior.Parse },
            { "PoisonedBehavior", PoisonedBehavior.Parse },
            { "PowerPlantUpdate", PowerPlantUpdate.Parse },
            { "PowerPlantUpgrade", PowerPlantUpgrade.Parse },
            { "PreorderCreate", PreorderCreate.Parse },
            { "ProductionUpdate", ProductionUpdate.Parse },
            { "RadarUpdate", RadarUpdate.Parse },
            { "RadarUpgrade", RadarUpgrade.Parse },
            { "RailedTransportContain", RailedTransportContain.Parse },
            { "RailedTransportDockUpdate", RailedTransportDockUpdate.Parse },
            { "RailedTransportAIUpdate", RailedTransportAIUpdate.Parse },
            { "RailroadBehavior", RailroadBehavior.Parse },
            { "RebuildHoleBehavior", RebuildHoleBehavior.Parse },
            { "RebuildHoleExposeDie", RebuildHoleExposeDie.Parse },
            { "SalvageCrateCollide", SalvageCrateCollide.Parse },
            { "SlowDeathBehavior", SlowDeathBehavior.Parse },
            { "SquishCollide", SquishCollide.Parse },
            { "SpecialAbility", SpecialAbility.Parse },
            { "SpecialPowerCreate", SpecialPowerCreate.Parse },
            { "SpyVisionSpecialPower", SpyVisionSpecialPower.Parse },
            { "SpyVisionUpdate", SpyVisionUpdate.Parse },
            { "StructureCollapseUpdate", StructureCollapseUpdate.Parse },
            { "StructureToppleUpdate", StructureToppleUpdate.Parse },
            { "SupplyWarehouseCreate", SupplyWarehouseCreate.Parse },
            { "SupplyWarehouseCripplingBehavior", SupplyWarehouseCripplingBehavior.Parse },
            { "SupplyWarehouseDockUpdate", SupplyWarehouseDockUpdate.Parse },
            { "TechBuildingBehavior", TechBuildingBehavior.Parse },
            { "TensileFormationUpdate", TensileFormationUpdate.Parse },
            { "ToppleUpdate", ToppleUpdate.Parse },
            { "TransitionDamageFX", TransitionDamageFX.Parse },
            { "TransportAIUpdate", TransportAIUpdate.Parse },
            { "TransportContain", TransportContain.Parse },
            { "UnitCrateCollide", UnitCrateCollide.Parse },
            { "VeterancyCrateCollide", VeterancyCrateCollide.Parse },
        };
    }
}
