version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
skip_tags: false

before_build:
- choco install opencover.portable
- choco install codecov

init:
- ps: >-
    $parsedReleaseBuildVersion = $env:APPVEYOR_REPO_TAG_NAME -Match "(\d+.\d+.\d+(.\d+)?)"
    
    if ($env:appveyor_repo_tag -AND $parsedReleaseBuildVersion) {
      $env:BuildVersion = $matches[0]
      $env:IsGithubRelease = $TRUE
    }
    else {
      $env:BuildVersion = $env:appveyor_build_version
      $env:IsGithubRelease = ""
    }

build_script:
- ps: |
      cd $env:APPVEYOR_BUILD_FOLDER\src\OpenSage.Game.Tests
      dotnet build -c $env:configuration -v m

      cd $env:APPVEYOR_BUILD_FOLDER\src\OpenSage.Launcher
      dotnet publish -c $env:configuration -o "$env:APPVEYOR_BUILD_FOLDER\build\artifacts\win-x64" -v m -r win-x64
      dotnet publish -c $env:configuration -o "$env:APPVEYOR_BUILD_FOLDER\build\artifacts\osx-x64" -v m -r osx-x64
      dotnet publish -c $env:configuration -o "$env:APPVEYOR_BUILD_FOLDER\build\artifacts\linux-x64" -v m -r linux-x64

artifacts:
- path: build\artifacts\win-x64
  name: win-x64
- path: build\artifacts\osx-x64
  name: osx-x64
- path: build\artifacts\linux-x64
  name: linux-x64

test_script:
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full C:\projects\opensage\src\OpenSage.Game.Tests\OpenSage.Game.Tests.csproj" -filter:"+[OpenSage*]* -[*.Tests*]*" -oldStyle -output:".\OpenSage_coverage.xml"
  - codecov -f "OpenSage_coverage.xml

cache:
  - '%USERPROFILE%\.nuget\packages'

deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: gd108UlSNyLViffYS7AKRgbTQXmzI6N/WgtNXFwkOsO9qGrWrAaJ853qAyv+FXp6
  artifact: win-x64, osx-x64, linux-x64
  description: "## Instructions\n1. Download the correct .zip file for your operating system\n2. Linux/Mac: export the path to your game path as an environment variable e.g.: `export CNC_GENERALS_PATH=~/generals/`\n3. Start the `OpenSage.Launcher` executable\n\n## Launcher\nThis executable will start OpenSAGE with the C&C Generals game files. To specify a different SAGE game, or see what other command line options are available, run `OpenSage.Launcher.exe --help`."
  draft: false
  prerelease: true
  on:
    branch: master
    IsGithubRelease: true