using System;
using OpenSage.Data.Ini;

namespace OpenSage.Logic.Object
{
    [AddedIn(SageGame.Bfme)]
    public enum AnimationType
    {
        None = 0,

        [IniEnum("FRONTKICKONBUILDING")]
        FrontKickOnBuilding,
        [IniEnum("IDLE")]
        Idle,
        [IniEnum("IDLA", "IdleA")]
        IdlA,
        [IniEnum("IDLB", "IdleB")]
        IdlB,
        [IniEnum("IDLC")]
        IdlC,
        [IniEnum("IDLD")]
        IdlD,
        [IniEnum("IDLF")]
        IdlF,
        [IniEnum("IDLG")]
        IdlG,
        [IniEnum("IDLH")]
        IdlH,
        [IniEnum("IDLI")]
        IdlI,
        [IniEnum("MOVING")]
        Moving,
        [IniEnum("STAND")]
        Stand,
        [IniEnum("WALK")]
        Walk,
        [IniEnum("WLKA")]
        WalkA,
        [IniEnum("WLKB")]
        WalkB,
        [IniEnum("WLKC")]
        WalkC,
        [IniEnum("BACKINGUP")]
        BackingUp,
        [IniEnum("DOUBLECHOP")]
        DoubleChop,
        [IniEnum("SIDEWAYSCHOP")]
        SidewaysChop,
        [IniEnum("VERTICALCHOP")]
        VerticalChop,
        [IniEnum("MFDA")]
        MfdA,
        [IniEnum("DIEA")]
        DieA,
        [IniEnum("DIEB")]
        DieB,
        [IniEnum("FLYA")]
        FlyA,
        [IniEnum("LNDA")]
        LndA,
        [IniEnum("STANDUP")]
        StandUp,
        [IniEnum("FERA")]
        FerA,
        [IniEnum("FERB")]
        FerB,
        [IniEnum("CHRA")]
        ChrA,
        [IniEnum("CHRB")]
        ChrB,
        [IniEnum("TNTA")]
        TntA,
        [IniEnum("TAUNTING2")]
        Taunting2,
        [IniEnum("APPA")]
        AppA,
        [IniEnum("HIT_LEVEL_1_A")]
        HitLevel1A,
        [IniEnum("WRKA")]
        WrkA,
        [IniEnum("WIPENOSE")]
        WipeNose,
        [IniEnum("SCRATCHBACK")]
        ScratchBack,
        [IniEnum("ATNB")]
        AtnB,
        [IniEnum("ATKA")]
        AtkA,
        [IniEnum("ATKB")]
        AtkB,
        [IniEnum("ATKC")]
        AtkC,
        [IniEnum("ROCKTHROW")]
        RockThrow,
        [IniEnum("RUNA")]
        RunA,
        [IniEnum("RUNB")]
        RunB,
        [IniEnum("CINEMATICSIGH")]
        CinematicSigh,
        [IniEnum("CINEMATICNERVOUSPUTONRING")]
        CinematicNervousPutOnRing,
        [IniEnum("GTPA")]
        GtpA,
        [IniEnum("STHA")]
        SthA,
        [IniEnum("MUMNTTROLL_GTPA")]
        MUMntTrollGTPA,
        [IniEnum("GRASPING_GROND_LEFTHANDED")]
        GraspingGrondLefthanded,
        [IniEnum("GRASPING_GROND_RIGHTHANDED")]
        GraspingGrondRighthanded,
        [IniEnum("SWINGING_GROND_LEFTHANDED")]
        SwingingGrondLefthanded,
        [IniEnum("SWINGING_GROND_RIGHTHANDED")]
        SwingingGrondRighthanded,
        [IniEnum("PACKING_GROND_RIGHTHANDED")]
        PackingGrondRighthanded,
        [IniEnum("PACKING_GROND_LEFTHANDED")]
        PackingGrondLefthanded,
        [IniEnum("PASSENGER_MOVING")]
        PassengerMoving,
        [IniEnum("PASSENGER")]
        Passenger,
        [IniEnum("CHARGING")]
        Charging,  
        [IniEnum("MOVING_DAMAGED")]
        MovingDamaged,
        [IniEnum("Moving_Engaged")]
        MovingEngaged,
        [IniEnum("RUNM")]
        RunM,
        [IniEnum("HIT_LEVEL_2")]
        HitLevel2,
        [IniEnum("HIT_LEVEL_3")]
        HitLevel3,
        [IniEnum("CLICK_REACT_1")]
        ClickReact1,
        [IniEnum("CLICK_REACT_2")]
        ClickReact2,
        [IniEnum("CLICK_REACT_3")]
        ClickReact3,
        [IniEnum("CLICK_REACT_4")]
        ClickReact4,
        [IniEnum("CLICK_REACT_5")]
        ClickReact5,
        [IniEnum("JustDie")]
        JustDie,
        [IniEnum("Land")]
        Land,
        [IniEnum("TerrorFromTheSky")]
        TerrorFromTheSky,
        [IniEnum("TurnLeft")]
        TurnLeft,
        [IniEnum("TurnRight")]
        TurnRight,
        [IniEnum("Accelerate")]
        Accelerate,
        [IniEnum("Decelerate")]
        Decelerate,
        [IniEnum("AttackA1")]
        AttackA1,
        [IniEnum("AttackA2")]
        AttackA2,
        [IniEnum("CheerA")]
        CheerA,
        [IniEnum("CheerB")]
        CheerB,
        [IniEnum("CheerC")]
        CheerC,
        [IniEnum("CheerD")]
        CheerD,
        [IniEnum("Salute")]
        Salute,
        [IniEnum("AtAttention")]
        AtAttention,
        [IniEnum("Taunting")]
        Taunting,
        [IniEnum("Moving_1")]
        Moving1,
        [IniEnum("Moving_2")]
        Moving2,
        [IniEnum("Splattered_On_Ground")]
        SplatteredOnGround,
        [IniEnum("Splattered_On_Ground_1")]
        SplatteredOnGround1,
        [IniEnum("Splattered_On_Ground_2")]
        SplatteredOnGround2,
        [IniEnum("Flaming_Death")]
        FlamingDeath,
        [IniEnum("Dying_1")]
        Dying1,
        [IniEnum("Dying_2")]
        Dying2,
        [IniEnum("Flying_1")]
        Flying_1,
        [IniEnum("Flying_2")]
        Flying_2,
        [IniEnum("Flying_3")]
        Flying_3,
        [IniEnum("Standing_Back_Up")]
        StandingBackUp,
        [IniEnum("StunFly")]
        StunFly,
        [IniEnum("DieStun")]
        DieStun,
        [IniEnum("DieStunB")]
        DieStunB,
        [IniEnum("March")]
        March,
        [IniEnum("Fly")]
        Fly,
        [IniEnum("StunDie")]
        StundDie,
        [IniEnum("Die")]
        Die,
        [IniEnum("SecondaryIdle")]
        SecondaryIdle,
        [IniEnum("FlyNDie")]
        FlyNDie,
        [IniEnum("Stunned")]
        Stunned,
        [IniEnum("DieAndSpawn")]
        DieAndSpawn,
        [IniEnum("DieAndNoSpawn")]
        DieAndNoSpawn,
        [IniEnum("GallopA")]
        GallopA,
        [IniEnum("GallopB")]
        GallopB,
        [IniEnum("Attack1")]
        Attack1,
        [IniEnum("Attack2")]
        Attack2,
        [IniEnum("Attack3")]
        Attack3,
        [IniEnum("Attack4")]
        Attack4,
        [IniEnum("Defend")]
        Defend,
    }
}
