using System;
using OpenSage.Data.Ini;

namespace OpenSage.Logic.Object
{
    [AddedIn(SageGame.Bfme)]
    public enum AnimationType
    {
        None = 0,

        [IniEnum("FRONTKICKONBUILDING")]
        FrontKickOnBuilding,
        [IniEnum("IDLA", "IdleA")]
        IdlA,
        [IniEnum("IDLB", "IdleB")]
        IdlB,
        [IniEnum("IDLC", "IdleC")]
        IdlC,
        [IniEnum("IDLD", "IdleD")]
        IdlD,
        [IniEnum("IDLE", "IdleE")]
        IdlE,
        [IniEnum("IDLF", "IdleF")]
        IdlF,
        [IniEnum("IDLG")]
        IdlG,
        [IniEnum("IDLH")]
        IdlH,
        [IniEnum("IDLI")]
        IdlI,
        [IniEnum("STAND")]
        Stand,
        [IniEnum("WALK")]
        Walk,
        [IniEnum("WLKA")]
        WalkA,
        [IniEnum("WLKB")]
        WalkB,
        [IniEnum("WLKC")]
        WalkC,
        [IniEnum("BACKINGUP")]
        BackingUp,
        [IniEnum("DOUBLECHOP")]
        DoubleChop,
        [IniEnum("SIDEWAYSCHOP")]
        SidewaysChop,
        [IniEnum("VERTICALCHOP")]
        VerticalChop,
        [IniEnum("MFDA")]
        MfdA,
        [IniEnum("DIEA")]
        DieA,
        [IniEnum("DIEB")]
        DieB,
        [IniEnum("FLYA")]
        FlyA,
        [IniEnum("LNDA")]
        LndA,
        [IniEnum("STANDUP")]
        StandUp,
        [IniEnum("FERA")]
        FerA,
        [IniEnum("FERB")]
        FerB,
        [IniEnum("CHRA")]
        ChrA,
        [IniEnum("CHRB")]
        ChrB,
        [IniEnum("TNTA")]
        TntA,
        [IniEnum("TAUNTING2")]
        Taunting2,
        [IniEnum("APPA")]
        AppA,
        [IniEnum("HIT_LEVEL_1_A")]
        HitLevel1A,
        [IniEnum("HIT_LEVEL_2_A")]
        HitLevel2A,
        [IniEnum("WRKA")]
        WrkA,
        [IniEnum("WIPENOSE")]
        WipeNose,
        [IniEnum("SCRATCHBACK")]
        ScratchBack,
        [IniEnum("ATNB")]
        AtnB,
        [IniEnum("ATKA", "AttackA")]
        AtkA,
        [IniEnum("ATKB", "AttackB")]
        AtkB,
        [IniEnum("ATKC", "AttackC")]
        AtkC,
        [IniEnum("ATKD", "AttackD")]
        AtkD,
        [IniEnum("ATKE", "AttackE")]
        AtkE,
        [IniEnum("ROCKTHROW")]
        RockThrow,
        [IniEnum("RUNA")]
        RunA,
        [IniEnum("RUNB")]
        RunB,
        [IniEnum("CINEMATICSIGH")]
        CinematicSigh,
        [IniEnum("CINEMATICNERVOUSPUTONRING")]
        CinematicNervousPutOnRing,
        [IniEnum("GTPA")]
        GtpA,
        [IniEnum("STHA")]
        SthA,
        [IniEnum("MUMNTTROLL_GTPA")]
        MUMntTrollGTPA,
        [IniEnum("GRASPING_GROND_LEFTHANDED")]
        GraspingGrondLefthanded,
        [IniEnum("GRASPING_GROND_RIGHTHANDED")]
        GraspingGrondRighthanded,
        [IniEnum("SWINGING_GROND_LEFTHANDED")]
        SwingingGrondLefthanded,
        [IniEnum("SWINGING_GROND_RIGHTHANDED")]
        SwingingGrondRighthanded,
        [IniEnum("PACKING_GROND_RIGHTHANDED")]
        PackingGrondRighthanded,
        [IniEnum("PACKING_GROND_LEFTHANDED")]
        PackingGrondLefthanded,
        [IniEnum("PASSENGER_MOVING")]
        PassengerMoving,
        [IniEnum("PASSENGER")]
        Passenger,
        [IniEnum("CHARGING")]
        Charging,
        [IniEnum("Move", "MOVING")]
        Move,
        [IniEnum("Move1", "Moving_1")]
        Move1,
        [IniEnum("Move2", "Moving_2")]
        Move2,
        [IniEnum("MOVING_DAMAGED", "Move_Damaged")]
        MovingDamaged,
        [IniEnum("Moving_Engaged")]
        MovingEngaged,
        [IniEnum("RUNM")]
        RunM,
        [IniEnum("HIT_LEVEL_2")]
        HitLevel2,
        [IniEnum("HIT_LEVEL_3")]
        HitLevel3,
        [IniEnum("CLICK_REACT_1")]
        ClickReact1,
        [IniEnum("CLICK_REACT_2")]
        ClickReact2,
        [IniEnum("CLICK_REACT_3")]
        ClickReact3,
        [IniEnum("CLICK_REACT_4")]
        ClickReact4,
        [IniEnum("CLICK_REACT_5")]
        ClickReact5,
        [IniEnum("JustDie")]
        JustDie,
        [IniEnum("Land")]
        Land,
        [IniEnum("TerrorFromTheSky")]
        TerrorFromTheSky,
        [IniEnum("TurnLeft", "TurningLeft")]
        TurnLeft,
        [IniEnum("TurnRight", "TurningRight")]
        TurnRight,
        [IniEnum("Accelerate")]
        Accelerate,
        [IniEnum("Decelerate")]
        Decelerate,
        [IniEnum("AttackA1")]
        AttackA1,
        [IniEnum("AttackA2")]
        AttackA2,
        [IniEnum("CheerA")]
        CheerA,
        [IniEnum("CheerB")]
        CheerB,
        [IniEnum("CheerC")]
        CheerC,
        [IniEnum("CheerD")]
        CheerD,
        [IniEnum("Salute")]
        Salute,
        [IniEnum("AtAttention")]
        AtAttention,
        [IniEnum("Taunting")]
        Taunting,
        [IniEnum("Splattered_On_Ground", "Splatted_On_Ground")]
        SplatteredOnGround,
        [IniEnum("Splattered_On_Ground_1")]
        SplatteredOnGround1,
        [IniEnum("Splattered_On_Ground_2")]
        SplatteredOnGround2,
        [IniEnum("Flaming_Death")]
        FlamingDeath,
        [IniEnum("Dying_1", "Die1")]
        Dying1,
        [IniEnum("Dying_2", "Die2")]
        Dying2,
        [IniEnum("Dying_3", "Die3")]
        Dying3,
        [IniEnum("Dying_4", "Die4")]
        Dying4,
        [IniEnum("Flying_1")]
        Flying_1,
        [IniEnum("Flying_2")]
        Flying_2,
        [IniEnum("Flying_3")]
        Flying_3,
        [IniEnum("Standing_Back_Up")]
        StandingBackUp,
        [IniEnum("StunFly")]
        StunFly,
        [IniEnum("DieStunB")]
        DieStunB,
        [IniEnum("March")]
        March,
        [IniEnum("Fly")]
        Fly,
        [IniEnum("StunDie", "DieStun")]
        StundDie,
        [IniEnum("Die")]
        Die,
        [IniEnum("SecondaryIdle")]
        SecondaryIdle,
        [IniEnum("FlyNDie")]
        FlyNDie,
        [IniEnum("Stunned")]
        Stunned,
        [IniEnum("DieAndSpawn")]
        DieAndSpawn,
        [IniEnum("DieAndNoSpawn")]
        DieAndNoSpawn,
        [IniEnum("GallopA")]
        GallopA,
        [IniEnum("GallopB")]
        GallopB,
        [IniEnum("Attack1")]
        Attack1,
        [IniEnum("Attack2")]
        Attack2,
        [IniEnum("Attack3")]
        Attack3,
        [IniEnum("Attack4")]
        Attack4,
        [IniEnum("Defend")]
        Defend,
        [IniEnum("IdleLook")]
        IdleLook,
        [IniEnum("WoundedIdle")]
        WoundedIdle,
        [IniEnum("GUFaramir_TOS3")]
        GUFaramirTOS3,
        [IniEnum("GUFaramir_STHA")]
        GUFaramirSTHA,
        [IniEnum("GUFaramir_STHB")]
        GUFaramir_STHB,
        [IniEnum("GUFaramir_IWKA")]
        GUFaramir_IWKA,
        [IniEnum("GUFaramir_WLKA")]
        GUFaramir_WLKA,
        [IniEnum("GUFaramir_RUNB")]
        GUFaramir_RUNB,
        [IniEnum("GUFaramir_ATKD")]
        GUFaramir_ATKD,
        [IniEnum("GUFaramir_LNDA")]
        GUFaramir_LNDA,
        [IniEnum("GUFaramir_DIEB")]
        GUFaramir_DIEB,
        [IniEnum("GUFaramir_FLYA")]
        GUFaramir_FLYA,
        [IniEnum("GUFaramir_GTPA")]
        GUFaramir_GTPA,
        [IniEnum("GUFaramir_IDLC")]
        GUFaramir_IDLC,
        [IniEnum("FLLA")]
        FLLA,
        [IniEnum("HITA")]
        HITA,
        [IniEnum("ATA1")]
        ATA1,
        [IniEnum("ATB1")]
        ATB1,
        [IniEnum("ATC1")]
        ATC1,
        [IniEnum("demoDie1")]
        DemoDie1,
        [IniEnum("demoDie2")]
        DemoDie2,
        [IniEnum("ALERT_1")]
        Alert1,
        [IniEnum("ALERT_2")]
        Alert2,
        [IniEnum("ALERT_3")]
        Alert3,
        [IniEnum("ALERT_4")]
        Alert4,
        [IniEnum("ATNA")]
        AtnA,
        [IniEnum("ATNC")]
        AtnC,
        [IniEnum("FERC")]
        FerC,
        [IniEnum("FERD")]
        FerD,
        [IniEnum("CHRC")]
        ChrC,
        [IniEnum("ReactionC")]
        ReactionC,
        [IniEnum("ReactionD")]
        ReactionD,
        [IniEnum("GUARD_STANCE")]
        GuardStance,
        [IniEnum("Apprehensive")]
        Apprehensive,
        [IniEnum("Apprehensive2")]
        Apprehensive2,
        [IniEnum("IDLL")]
        IdlL,
        [IniEnum("IDLM")]
        IdlM,
        [IniEnum("IDLN")]
        IdlN,
        [IniEnum("IDLK")]
        IdlK,
        [IniEnum("IDLO")]
        IdlO,
        [IniEnum("IDLP")]
        IdlP,
        [IniEnum("IDLJ")]
        IdlJ,
        [IniEnum("Thrown")]
        Thrown,
        [IniEnum("BackingUpA")]
        BackingUpA,
        [IniEnum("BackingUpB")]
        BackingUpB,
        [IniEnum("Climbing_Down")]
        ClimbingDown,
        [IniEnum("Climbing_Up")]
        ClimbingUp,
        [IniEnum("Wiggle")]
        Wiggle,
        [IniEnum("SelectedIDLA")]
        SelectedIdlA,
        [IniEnum("Taunting3")]
        Taunting3,
        [IniEnum("RCTA")]
        RctA,
        [IniEnum("IDLES")]
        IdleS,
        [IniEnum("GUSiegTreb_TNSL")]
        GUsiegTrebTNSL,
        [IniEnum("GUSiegTreb_TNSR")]
        GUsiegTrebTNSR,
        [IniEnum("GUSiegTreb_ATAK")]
        GUsiegTrebATAK,
        [IniEnum("GUSiegTreb_TRNL")]
        GUsiegTrebTRNL,
        [IniEnum("GUSiegTreb_TRNR")]
        GUsiegTrebTRNR,
        [IniEnum("GUSiegTreb_DIEC")]
        GUsiegTrebDieC,
        [IniEnum("GUSiegTreb_DIEE")]
        GUsiegTrebDieE,
        [IniEnum("GUSiegTreb_DIED")]
        GUsiegTrebDieD,
        [IniEnum("GUSiegTreb_DIEB")]
        GUsiegTrebDieB,
        [IniEnum("GUSiegTreb_DIEA")]
        GUsiegTrebDieA,
        [IniEnum("GUSiegTreRk")]
        GUsiegTreRk,
        [IniEnum("RousingSpeech")]
        RousingSpeech,
        [IniEnum("DamagedIdle")]
        DamagedIdle,
        [IniEnum("Idle1")]
        Idle1,
        [IniEnum("MUCatapult_FP01")]
        MUCatapultFP01,
        [IniEnum("Wander1")]
        Wander1,
        [IniEnum("Wander2")]
        Wander2,
        [IniEnum("Fire")]
        Fire,
        [IniEnum("StunFlail")]
        StunFlail,
        [IniEnum("SLTA")]
        SLTA,
        [IniEnum("GUARD_CHEER")]
        GuardCheer,
        [IniEnum("MoveIt")]
        MoveIt,
        [IniEnum("Turn")]
        Turn,
        [IniEnum("Rampage")]
        Rampage,
        [IniEnum("Charge")]
        Charge,
        [IniEnum("dead1")]
        Dead1,
        [IniEnum("dead2")]
        Dead2,
        [IniEnum("dead3")]
        Dead3,
        [IniEnum("Transition")]
        Transition,
        [IniEnum("Being_Built")]
        BeingBuilt,
    }
}
