using System;
using System.Collections.Generic;
using OpenSage.Data.Ini.Parser;

namespace OpenSage.Logic.Object
{
    public abstract class ObjectBehavior : ObjectModule
    {
        internal static ObjectBehavior ParseBehavior(IniParser parser) => ParseModule(parser, BehaviorParseTable);

        private static readonly Dictionary<string, Func<IniParser, ObjectBehavior>> BehaviorParseTable = new Dictionary<string, Func<IniParser, ObjectBehavior>>
        {
            { "AIUpdateInterface", AIUpdateInterface.Parse },
            { "AssistedTargetingUpdate", AssistedTargetingUpdate.Parse },
            { "AutoDepositUpdate", AutoDepositUpdate.Parse },
            { "AutoFindHealingUpdate", AutoFindHealingUpdate.Parse },
            { "AutoHealBehavior", AutoHealBehavior.Parse },
            { "BaikonurLaunchPower", BaikonurLaunchPower.Parse },
            { "BaseRegenerateUpdate", BaseRegenerateUpdate.Parse },
            { "BattlePlanUpdate", BattlePlanUpdate.Parse },
            { "BoneFXDamage", BoneFXDamage.Parse },
            { "BoneFXUpdate", BoneFXUpdate.Parse },
            { "BridgeBehavior", BridgeBehavior.Parse },
            { "BridgeTowerBehavior", BridgeTowerBehavior.Parse },
            { "CashBountyPower", CashBountyPower.Parse },
            { "CashHackSpecialPower", CashHackSpecialPower.Parse },
            { "CheckpointUpdate", CheckpointUpdate.Parse },
            { "CleanupAreaPower", CleanupAreaPower.Parse },
            { "CleanupHazardUpdate", CleanupHazardUpdate.Parse },
            { "CommandButtonHuntUpdate", CommandButtonHuntUpdate.Parse },
            { "ConvertToCarBombCrateCollide", ConvertToCarBombCrateCollide.Parse },
            { "ConvertToHijackedVehicleCrateCollide", ConvertToHijackedVehicleCrateCollide.Parse },
            { "CostModifierUpgrade", CostModifierUpgrade.Parse },
            { "CreateCrateDie", CreateCrateDie.Parse },
            { "CreateObjectDie", CreateObjectDie.Parse },
            { "CrushDie", CrushDie.Parse },
            { "DamDie", DamDie.Parse },
            { "DefaultProductionExitUpdate", DefaultProductionExitUpdate.Parse },
            { "DefectorSpecialPower", DefectorSpecialPower.Parse },
            { "DeletionUpdate", DeletionUpdate.Parse },
            { "DeliverPayloadAIUpdate", DeliverPayloadAIUpdate.Parse },
            { "DemoTrapUpdate", DemoTrapUpdate.Parse },
            { "DestroyDie", DestroyDie.Parse },
            { "DynamicShroudClearingRangeUpdate", DynamicShroudClearingRangeUpdate.Parse },
            { "EjectPilotDie", EjectPilotDie.Parse },
            { "EnemyNearUpdate", EnemyNearUpdate.Parse },
            { "ExperienceScalarUpgrade", ExperienceScalarUpgrade.Parse },
            { "FireOCLAfterWeaponCooldownUpdate", FireOCLAfterWeaponCooldownUpdate.Parse },
            { "FireWeaponWhenDeadBehavior", FireWeaponWhenDeadBehavior.Parse },
            { "FireWeaponWhenDamagedBehavior", FireWeaponWhenDamagedBehavior.Parse },
            { "FlammableUpdate", FlammableUpdate.Parse },
            { "FloatUpdate", FloatUpdate.Parse },
            { "FXListDie", FXListDie.Parse },
            { "GarrisonContain", GarrisonContain.Parse },
            { "GenerateMinefieldBehavior", GenerateMinefieldBehavior.Parse },
            { "GrantUpgradeCreate", GrantUpgradeCreate.Parse },
            { "HealContain", HealContain.Parse },
            { "HeightDieUpdate", HeightDieUpdate.Parse },
            { "HelicopterSlowDeathBehavior", HelicopterSlowDeathBehavior.Parse },
            { "HijackerUpdate", HijackerUpdate.Parse },
            { "HordeUpdate", HordeUpdate.Parse },
            { "InstantDeathBehavior", InstantDeathBehavior.Parse },
            { "KeepObjectDie", KeepObjectDie.Parse },
            { "JetAIUpdate", JetAIUpdate.Parse },
            { "JetSlowDeathBehavior", JetSlowDeathBehavior.Parse },
            { "LifetimeUpdate", LifetimeUpdate.Parse },
            { "LocomotorSetUpgrade", LocomotorSetUpgrade.Parse },
            { "MinefieldBehavior", MinefieldBehavior.Parse },
            { "MissileAIUpdate", MissileAIUpdate.Parse },
            { "MissileLauncherBuildingUpdate", MissileLauncherBuildingUpdate.Parse },
            { "MobMemberSlavedUpdate", MobMemberSlavedUpdate.Parse },
            { "MoneyCrateCollide", MoneyCrateCollide.Parse },
            { "MaxHealthUpgrade", MaxHealthUpgrade.Parse },
            { "NeutronMissileSlowDeathBehavior", NeutronMissileSlowDeathBehavior.Parse },
            { "NeutronMissileUpdate", NeutronMissileUpdate.Parse },
            { "OCLSpecialPower", OCLSpecialPower.Parse },
            { "OCLUpdate", OCLUpdate.Parse },
            { "ObjectCreationUpgrade", ObjectCreationUpgrade.Parse },
            { "OverchargeBehavior", OverchargeBehavior.Parse },
            { "OverlordContain", OverlordContain.Parse },
            { "ParachuteContain", ParachuteContain.Parse },
            { "ParkingPlaceBehavior", ParkingPlaceBehavior.Parse },
            { "ParticleUplinkCannonUpdate", ParticleUplinkCannonUpdate.Parse },
            { "PhysicsBehavior", PhysicsBehavior.Parse },
            { "PilotFindVehicleUpdate", PilotFindVehicleUpdate.Parse },
            { "PoisonedBehavior", PoisonedBehavior.Parse },
            { "PowerPlantUpdate", PowerPlantUpdate.Parse },
            { "PowerPlantUpgrade", PowerPlantUpgrade.Parse },
            { "PreorderCreate", PreorderCreate.Parse },
            { "ProductionUpdate", ProductionUpdate.Parse },
            { "ProjectileStreamUpdate", ProjectileStreamUpdate.Parse },
            { "PropagandaTowerBehavior", PropagandaTowerBehavior.Parse },
            { "QueueProductionExitUpdate", QueueProductionExitUpdate.Parse },
            { "RadarUpdate", RadarUpdate.Parse },
            { "RadarUpgrade", RadarUpgrade.Parse },
            { "RadiusDecalUpdate", RadiusDecalUpdate.Parse },
            { "RailedTransportContain", RailedTransportContain.Parse },
            { "RailedTransportDockUpdate", RailedTransportDockUpdate.Parse },
            { "RailedTransportAIUpdate", RailedTransportAIUpdate.Parse },
            { "RailroadBehavior", RailroadBehavior.Parse },
            { "RebuildHoleBehavior", RebuildHoleBehavior.Parse },
            { "RebuildHoleExposeDie", RebuildHoleExposeDie.Parse },
            { "RepairDockUpdate", RepairDockUpdate.Parse },
            { "SalvageCrateCollide", SalvageCrateCollide.Parse },
            { "SlavedUpdate", SlavedUpdate.Parse },
            { "SlowDeathBehavior", SlowDeathBehavior.Parse },
            { "SquishCollide", SquishCollide.Parse },
            { "SpawnBehavior", SpawnBehavior.Parse },
            { "SpawnPointProductionExitUpdate", SpawnPointProductionExitUpdate.Parse },
            { "SpecialAbility", SpecialAbility.Parse },
            { "SpecialAbilityUpdate", SpecialAbilityUpdate.Parse },
            { "SpecialPowerCompletionDie", SpecialPowerCompletionDie.Parse },
            { "SpecialPowerCreate", SpecialPowerCreate.Parse },
            { "SpyVisionSpecialPower", SpyVisionSpecialPower.Parse },
            { "SpyVisionUpdate", SpyVisionUpdate.Parse },
            { "StealthDetectorUpdate", StealthDetectorUpdate.Parse },
            { "StealthUpdate", StealthUpdate.Parse },
            { "StealthUpgrade", StealthUpgrade.Parse },
            { "StickyBombUpdate", StickyBombUpdate.Parse },
            { "StructureCollapseUpdate", StructureCollapseUpdate.Parse },
            { "StructureToppleUpdate", StructureToppleUpdate.Parse },
            { "SubObjectsUpgrade", SubObjectsUpgrade.Parse },
            { "SupplyCenterCreate", SupplyCenterCreate.Parse },
            { "SupplyCenterDockUpdate", SupplyCenterDockUpdate.Parse },
            { "SupplyCenterProductionExitUpdate", SupplyCenterProductionExitUpdate.Parse },
            { "SupplyWarehouseCreate", SupplyWarehouseCreate.Parse },
            { "SupplyWarehouseCripplingBehavior", SupplyWarehouseCripplingBehavior.Parse },
            { "SupplyWarehouseDockUpdate", SupplyWarehouseDockUpdate.Parse },
            { "TechBuildingBehavior", TechBuildingBehavior.Parse },
            { "TensileFormationUpdate", TensileFormationUpdate.Parse },
            { "ToppleUpdate", ToppleUpdate.Parse },
            { "TransitionDamageFX", TransitionDamageFX.Parse },
            { "TransportAIUpdate", TransportAIUpdate.Parse },
            { "TransportContain", TransportContain.Parse },
            { "TunnelContain", TunnelContain.Parse },
            { "UnitCrateCollide", UnitCrateCollide.Parse },
            { "UnpauseSpecialPowerUpgrade", UnpauseSpecialPowerUpgrade.Parse },
            { "UpgradeDie", UpgradeDie.Parse },
            { "VeterancyCrateCollide", VeterancyCrateCollide.Parse },
            { "VeterancyGainCreate", VeterancyGainCreate.Parse },
            { "WeaponBonusUpgrade", WeaponBonusUpgrade.Parse },
            { "WeaponSetUpgrade", WeaponSetUpgrade.Parse },
            { "WorkerAIUpdate", WorkerAIUpdate.Parse },
        };
    }
}
