namespace OpenSage.Scripting;

// TODO: Check if BFME reused existing ScriptArgumentType values. It probably did...
// in which case we'll need a ScriptArgumentType per game.
public enum ScriptArgumentType : uint
{
    Int = 0,
    Real = 1,
    Script = 2,
    Team = 3,
    Counter = 4,
    Flag = 5,
    Comparison = 6,
    Waypoint = 7,
    Boolean = 8,
    TriggerArea = 9,
    TextString = 10,
    Side = 11,
    Sound = 12,
    ScriptSubroutine = 13,
    Unit = 14,
    ObjectType = 15,
    Coord3D = 16,
    Angle = 17,
    TeamState = 18,
    Relation = 19,
    AiMood = 20,
    Dialog = 21,
    Music = 22,
    Movie = 23,
    WaypointPath = 24,
    LocalizedText = 25,
    Bridge = 26,
    KindOfParam = 27,
    AttackPrioritySet = 28,
    RadarEventType = 29,
    SpecialPower = 30,
    Science = 31,
    Upgrade = 32,
    CommandButtonAbility = 33,
    Boundary = 34,
    Buildable = 35,
    SurfacesAllowed = 36,
    ShakeIntensity = 37,
    CommandButton = 38,
    FontName = 39,
    ObjectStatus = 40,
    CommandButtonAllAbilities = 41,
    SkirmishWaypointPath = 42,
    Color = 43,
    Emoticon = 44,
    ObjectPanelFlag = 45,
    FactionName = 46,
    ObjectTypeList = 47,
    RevealName = 48,
    ScienceAvailability = 49,
    LeftOrRight = 50,
    Percent = 51,

    // Added in BFME
    Percentage2 = 52, // Dupe of 51, perhaps because BFME and ZH development overlapped?
    UnitReference = 54,
    TeamReference = 55,
    NearOrFar = 56,
    MathOperator = 57,
    ModelCondition = 58,
    AudioName = 59,
    ReverbRoomType = 60,
    ObjectType2 = 61,
    Hero = 62,
    Emotion = 63,
}
