using System;

namespace OpenSage.FileFormats.Apt
{
    public static class Constants
    {
        public const string AptFileMagic = "Apt Data:74\x1A\x00\x00\x00\x00";
        public const string ConstFileMagic = "Apt constant file\x1A\x00\x00";
        public const uint IntPtrSize = 4;
        public const UInt64 DefineFunctionUnknownNumber = 1311768467425612850;
        public const string OpenSageAptEditorCredits = "Generated by OpenSage Apt Editor";
    }
}
