using OpenSage.Data.Ini;

namespace OpenSage.Logic.Object;

// Order of these values is from a comment in DamageFX.ini
// items with explicit indexes have been verified against saves generated by Generals
public enum DamageType
{
    [IniEnum("EXPLOSION")]
    Explosion = 0,

    [IniEnum("CRUSH")]
    Crush = 1,

    [IniEnum("ARMOR_PIERCING")]
    ArmorPiercing = 2,

    [IniEnum("SMALL_ARMS")]
    SmallArms = 3,

    [IniEnum("GATTLING")]
    Gattling = 4, // [sic]

    [IniEnum("RADIATION")]
    Radiation = 5,

    [IniEnum("FLAME")]
    Flame = 6,

    [IniEnum("LASER")]
    Laser = 7,

    [IniEnum("SNIPER")]
    Sniper = 8,

    [IniEnum("POISON")]
    Poison = 9,

    [IniEnum("HEALING")]
    Healing = 10,

    /// <summary>
    /// This is for scripting to cause "armorproof" damage.
    /// </summary>
    [IniEnum("UNRESISTABLE")]
    Unresistable = 11,

    [IniEnum("WATER")]
    Water = 12,

    /// <summary>
    /// For transports to deploy units and order them to all attack.
    /// </summary>
    [IniEnum("DEPLOY")]
    Deploy = 13,

    /// <summary>
    /// If something "dies" to surrender damage, they surrender.
    /// </summary>
    [IniEnum("SURRENDER")]
    Surrender = 14,

    [IniEnum("HACK")]
    Hack = 15,

    /// <summary>
    /// Special snipe attack that kills the pilot and renders a vehicle unmanned.
    /// </summary>
    [IniEnum("KILL_PILOT")]
    KillPilot = 16,

    /// <summary>
    /// From game penalty (you won't receive radar warnings).
    /// </summary>
    [IniEnum("PENALTY")]
    Penalty = 17,

    [IniEnum("FALLING")]
    Falling = 18,

    /// <summary>
    /// Blades, clubs, etc.
    /// </summary>
    [IniEnum("MELEE")]
    Melee = 19,

    /// <summary>
    /// "Special" damage type used for disarming mines, bombs, etc.
    /// (_not_ for disarming an opponent!)
    /// </summary>
    [IniEnum("DISARM")]
    Disarm = 20,

    /// <summary>
    /// Special damage type for cleaning up hazards like radiation or bio-poison.
    /// </summary>
    [IniEnum("HAZARD_CLEANUP")]
    HazardCleanup = 21,

    /// <summary>
    /// Incinerates virtually everything (insanely powerful orbital beam).
    /// </summary>
    [IniEnum("PARTICLE_BEAM")]
    ParticleBeam = 22,

    /// <summary>
    /// Damage from getting toppled.
    /// </summary>
    [IniEnum("TOPPLING")]
    Toppling = 23,

    [IniEnum("INFANTRY_MISSILE")]
    InfantryMissile = 24,

    [IniEnum("AURORA_BOMB")]
    AuroraBomb = 25,

    [IniEnum("LAND_MINE")]
    LandMine = 26,

    [IniEnum("JET_MISSILES")]
    JetMissiles = 27,

    [IniEnum("STEALTHJET_MISSILES")]
    StealthjetMissiles = 28,

    [IniEnum("MOLOTOV_COCKTAIL")]
    MolotovCocktail = 29,

    [IniEnum("COMANCHE_VULCAN")]
    ComancheVulcan = 30,

    [IniEnum("FLESHY_SNIPER")]
    FleshySniper = 31,

    /// <summary>
    /// Damage that does not kill you, but produces some special effect based
    /// on your Body Module. Separate HP from normal damage.
    /// </summary>
    [IniEnum("SUBDUAL_MISSILE"), AddedIn(SageGame.CncGeneralsZeroHour)]
    SubdualMissile = 31, // Yes, it used the same value as Generals' FLESHY_SNIPER

    [IniEnum("SUBDUAL_VEHICLE"), AddedIn(SageGame.CncGeneralsZeroHour)]
    SubdualVehicle = 32,

    [IniEnum("SUBDUAL_BUILDING"), AddedIn(SageGame.CncGeneralsZeroHour)]
    SubdualBuilding = 33,

    [IniEnum("SUBDUAL_UNRESISTABLE"), AddedIn(SageGame.CncGeneralsZeroHour)]
    SubdualUnresistable = 34,

    /// <summary>
    /// Radiation that only affects infantry.
    /// </summary>
    [IniEnum("MICROWAVE"), AddedIn(SageGame.CncGeneralsZeroHour)]
    Microwave = 35,

    /// <summary>
    /// Kills passengers up to the number specified in damage.
    /// </summary>
    [IniEnum("KILL_GARRISONED"), AddedIn(SageGame.CncGeneralsZeroHour)]
    KillGarrisoned = 36,

    /// <summary>
    /// Damage that gives a status condition, not that does hitpoint damage.
    /// </summary>
    [IniEnum("STATUS"), AddedIn(SageGame.CncGeneralsZeroHour)]
    Status = 37,

    [IniEnum("SLASH"), AddedIn(SageGame.Bfme)]
    Slash,

    [IniEnum("PIERCE"), AddedIn(SageGame.Bfme)]
    Pierce,

    [IniEnum("URUK"), AddedIn(SageGame.Bfme)]
    Uruk,

    [IniEnum("HERO"), AddedIn(SageGame.Bfme)]
    Hero,

    [IniEnum("HERO_RANGED"), AddedIn(SageGame.Bfme)]
    HeroRanged,

    [IniEnum("SIEGE"), AddedIn(SageGame.Bfme)]
    Siege,

    [IniEnum("SPECIALIST"), AddedIn(SageGame.Bfme)]
    Specialist,

    [IniEnum("MAGIC"), AddedIn(SageGame.Bfme)]
    Magic,

    [IniEnum("STRUCTURAL"), AddedIn(SageGame.Bfme)]
    Structural,

    [IniEnum("CHOP"), AddedIn(SageGame.Bfme)]
    Chop,

    [IniEnum("FORCE"), AddedIn(SageGame.Bfme)]
    Force,

    [IniEnum("FLY_INTO"), AddedIn(SageGame.Bfme)]
    FlyInto,

    [IniEnum("GOOD_ARROW_PIERCE"), AddedIn(SageGame.Bfme)]
    GoodArrowPierce,

    [IniEnum("EVIL_ARROW_PIERCE"), AddedIn(SageGame.Bfme)]
    EvilArrowPierce,

    [IniEnum("SWORD_SLASH"), AddedIn(SageGame.Bfme)]
    SwordSlash,

    [IniEnum("WITCH_KING_MORGUL_BLADE"), AddedIn(SageGame.Bfme)]
    WitchKingMorgulBlade,

    [IniEnum("REFLECTED"), AddedIn(SageGame.Bfme)]
    Reflected,

    [IniEnum("BALROG_SWORD"), AddedIn(SageGame.Bfme)]
    BalrogSword,

    [IniEnum("BALROG_WHIP"), AddedIn(SageGame.Bfme)]
    BalrogWhip,

    [IniEnum("ELECTRIC"), AddedIn(SageGame.Bfme)]
    Electric,

    [IniEnum("GIMLI_LEAP"), AddedIn(SageGame.Bfme)]
    GimliLeap,

    [IniEnum("BIG_ROCK"), AddedIn(SageGame.Bfme)]
    BigRock,

    [IniEnum("CLUBBING"), AddedIn(SageGame.Bfme)]
    Clubbing,

    [IniEnum("BECOME_UNDEAD"), AddedIn(SageGame.Bfme2)]
    BecomeUndead,

    [IniEnum("CAVALRY_RANGED"), AddedIn(SageGame.Bfme2)]
    CavalryRanged,

    [IniEnum("CAVALRY"), AddedIn(SageGame.Bfme2)]
    Cavalry,

    [IniEnum("LOGICAL_FIRE"), AddedIn(SageGame.Bfme2)]
    LogicalFire,

    [IniEnum("BOLT"), AddedIn(SageGame.Bfme2)]
    Bolt,

    [IniEnum("TORNADO"), AddedIn(SageGame.Bfme2)]
    Tornado,

    [IniEnum("FLOOD_HORSE"), AddedIn(SageGame.Bfme2)]
    FloodHorse,

    [IniEnum("FIRE3"), AddedIn(SageGame.Bfme2)]
    Fire3,

    [IniEnum("BECOME_UNDEAD_ONCE"), AddedIn(SageGame.Bfme2Rotwk)]
    BecomeUndeadOnce,

    [IniEnum("FROST"), AddedIn(SageGame.Bfme2Rotwk)]
    Frost,

    [IniEnum("NECRO1"), AddedIn(SageGame.Bfme2Rotwk)]
    Necro1,

    [IniEnum("NECRO2"), AddedIn(SageGame.Bfme2Rotwk)]
    Necro2,
}
