name: Format

on:
  push:
  pull_request:
  merge_group:

jobs:
  format:
    name: Validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Check formatting
      run: dotnet format src --verify-no-changes --verbosity diagnostic
